<a href="https://colab.research.google.com/github/ptoledoc7/Prueba/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df1 = pd.read_excel('ETL C1.xls')
df2 = pd.read_excel('ETL C2.xls')
df3 = pd.read_excel('ETL C3.xls')

# Dataframe

In [4]:
df1 #visualizar datos de cada dataframe

          rut                     nombre_completo sexo  edad
0   182834860       Carmen Andrea Flores González    F  39.0
1   144214022       Alicia Marcela Aguirre Guerra    F  37.0
2   179898366           Ernesto Luis Sabato Marin    M  36.0
3   196052553           Iván Andrés Cabrera Marin    M  67.0
4   135893930     Marcos Marcelo Hernandez Lozano    M  66.0
5   173452870           Pedro Andrés Salas Pratto    M  59.0
6   177897092           Lucas Andrés Pratto Marin    M  48.0
7   167247766         Judas Jesús Prieto González    M  55.0
8   118582643           Luis Marcelo Diaz Carmela    M  67.0
9   141741407        Andrés Luis Poblete González    M  42.0
10  135196356        Juana Lucia Arco Estibarriga    F  35.0
11  147503985          Luisa Juana Rojas Chamorro    F  34.0
12  103952108         Irma Daniela González Rosas    F  41.0
13  168247476       Luisa Marcela Rojas Rodriguez    F   NaN
14  178041143     Andrés Marcelo Carmona Carvajal    M   NaN
15  166892378        Pedro Luis Carmona Rodriguez  NaN   NaN
16  162665681       Juan Martin Del Potro Salazar    M   NaN
17  171304656       Walter Montillo Soto González    M   NaN
18  126189782      Marcelo Rios González González  NaN   NaN
19  151971103        Marcelo Francisco Soto Rojas    M   NaN
20  153743010         Iván Marcelo González Rosas    M   NaN
21  114967552     Marcela María Zabaletta Zanetta    F   NaN
22  156686434  Andrea Marcela Quinchamali Marchan  NaN   NaN
23  141919046  Macarena Daniela Rodriguez Altibán    F   NaN
24  195723005       Roberta Sofia González Barros    F   NaN
25  191125557              Andrea Luisa Marin Roa    F   NaN
26  182397153       María María González González    F   NaN
27  139926953            Juana Luisa Marin Natero    F   NaN
28  124974492   María De Los Ángeles Lozano Marin    F   NaN

In [5]:
df2

,rut,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,edad
0,18283486-0,Carmen,Andrea,Flores,González,39.0
1,14421402-2,Alicia,Marcela,Aguirre,Guerra,37.0
2,17989836-6,Ernesto,Luis,Sabato,Marin,36.0
3,19605255-3,Iván,Andrés,Cabrera,Marin,67.0
4,13589393-0,Marcos,Marcelo,Hernandez,Lozano,NaN
5,17345287-0,Pedro,Andrés,Salas,Pratto,59.0
6,17789709-2,Lucas,Andrés,Pratto,Marin,48.0
7,16724776-6,Judas,Jesús,Prieto,González,55.0
8,11858264-3,Luis,Marcelo,Diaz,Carmela,67.0
9,14174140-7,Andrés,Luis,Poblete,González,42.0
10,13519635-6,Juana,Lucia,Arco,Estibarriga,NaN
11,14750398-5,Luisa,Juana,Rojas,Chamorro,NaN
12,10395210-8,Irma,Daniela,González,Rosas,NaN
13,16824747-6,Luisa,Marcela,Rojas,Rodriguez,18.0
14,17804114-3,Andrés,Marcelo,Carmona,Carvajal,23.0
15,16689237-8,Pedro,Luis,Carmona,Rodriguez,45.0
16,16266568-1,Juan,Martin,Del Potro,Salazar,59.0
17,17130465-6,Walter,Montillo,Soto,González,NaN
18,12618978-2,Marcelo,Rios,González,González,NaN
19,15197110-3,Marcelo,Francisco,Soto,Rojas,NaN
20,15374301-0,Iván,Marcelo,González,Rosas,NaN
21,11496755-2,Marcela,María,Zabaletta,Zanetta,NaN
22,15668643-4,Andrea,Marcela,Quinchamali,Marchan,NaN
23,14191904-6,Macarena,Daniela,Rodriguez,Altibán,NaN
24,19572300-5,Roberta,Sofia,González,Barros,NaN
25,19112555-7,Andrea,Luisa,Marin,Roa,NaN
26,18239715-3,María,María,González,González,NaN
27,13992695-3,Juana,Luisa,Marin,Natero,NaN
28,12497449-2,María,De Los Ángeles,Lozano,Marin,NaN

In [6]:
df3

          rut primer_nombre primer_apellido  sexo     edad
0   182834860        Carmen          Flores   1.0  39 años
1   144214022        Alicia         Aguirre   NaN  37 años
2   179898366       Ernesto          Sabato   0.0  36 años
3   196052553          Iván         Cabrera   0.0  67 años
4   135893930        Marcos       Hernandez   0.0  66 años
5   173452870         Pedro           Salas   0.0  59 años
6   177897092         Lucas          Pratto   NaN  48 años
7   167247766         Judas          Prieto   0.0  55 años
8   118582643          Luis            Diaz   0.0  67 años
9   141741407        Andrés         Poblete   0.0      NaN
10  135196356         Juana            Arco   1.0      NaN
11  147503985         Luisa           Rojas   1.0  34 años
12  103952108          Irma        González   1.0      NaN
13  168247476         Luisa           Rojas   1.0      NaN
14  178041143        Andrés         Carmona   0.0      NaN
15  166892378         Pedro         Carmona   NaN      NaN
16  162665681          Juan       Del Potro   0.0      NaN
17  171304656        Walter            Soto   0.0  34 años
18  126189782       Marcelo        González   0.0  50 años
19  151971103       Marcelo            Soto   0.0  55 años
20  153743010          Iván        González   0.0  64 años
21  114967552       Marcela       Zabaletta   1.0  63 años
22  156686434        Andrea     Quinchamali   NaN  52 años
23  141919046      Macarena       Rodriguez   1.0  58 años
24  195723005       Roberta        González   1.0  64 años
25  191125557        Andrea           Marin   1.0  26 años
26  182397153         María        González   1.0  61 años
27  139926953         Juana           Marin   1.0  45 años
28  124974492         María          Lozano   1.0  46 años

Analizar

In [7]:
df1.columns

Index(['rut', 'nombre_completo', 'sexo', 'edad'], dtype='object')

In [8]:
df2.columns

Index(['rut', 'primer_nombre', 'segundo_nombre', 'primer_apellido',
       'segundo_apellido', 'edad'],
      dtype='object')

In [9]:
df3.columns

Index(['rut', 'primer_nombre', 'primer_apellido', 'sexo', 'edad'], dtype='object')

In [10]:
df1.dtypes #de que tipo son los atributos

rut                  int64
nombre_completo     object
sexo                object
edad               float64
dtype: object

In [11]:
df2.dtypes

rut                  object
primer_nombre        object
segundo_nombre       object
primer_apellido      object
segundo_apellido     object
edad                float64
dtype: object

In [12]:
df3.dtypes

rut                  int64
primer_nombre       object
primer_apellido     object
sexo               float64
edad                object
dtype: object

In [13]:
df1.describe(include=['object']) #atributos tipo string

                      nombre_completo sexo
count                              29   26
unique                             29    2
top     Carmen Andrea Flores González    F
freq                                1   13

In [14]:
df2.describe(include=['object'])

,rut,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido
count,29,29,29,29,29
unique,29,21,17,21,19
top,18283486-0,Juana,Marcelo,González,González
freq,1,2,4,5,6

In [15]:
df3.describe(include=['object'])

       primer_nombre primer_apellido     edad
count             29              29       22
unique            21              21       18
top            Juana        González  67 años
freq               2               5        2

In [16]:
df1.describe(include=np.number) #atributos tipo numerico

                rut       edad
count  2.900000e+01  13.000000
mean   1.562498e+08  48.153846
std    2.515643e+07  12.947626
min    1.039521e+08  34.000000
25%    1.399270e+08  37.000000
50%    1.566864e+08  42.000000
75%    1.778971e+08  59.000000
max    1.960526e+08  67.000000

In [17]:
df2.describe(include=np.number)

            edad
count  13.000000
mean   45.769231
std    15.449670
min    18.000000
25%    37.000000
50%    45.000000
75%    59.000000
max    67.000000

In [18]:
df3.describe(include=np.number)

                rut       sexo
count  2.900000e+01  25.000000
mean   1.562498e+08   0.480000
std    2.515643e+07   0.509902
min    1.039521e+08   0.000000
25%    1.399270e+08   0.000000
50%    1.566864e+08   0.000000
75%    1.778971e+08   1.000000
max    1.960526e+08   1.000000

In [19]:
df1.nunique()

rut                29
nombre_completo    29
sexo                2
edad               12
dtype: int64

In [20]:
df2.nunique()

rut                 29
primer_nombre       21
segundo_nombre      17
primer_apellido     21
segundo_apellido    19
edad                11
dtype: int64

In [21]:
df3.nunique()

rut                29
primer_nombre      21
primer_apellido    21
sexo                2
edad               18
dtype: int64

In [22]:
pd.isna(df1).sum()

rut                 0
nombre_completo     0
sexo                3
edad               16
dtype: int64

In [23]:
pd.isna(df2).sum()

rut                  0
primer_nombre        0
segundo_nombre       0
primer_apellido      0
segundo_apellido     0
edad                16
dtype: int64

In [24]:
pd.isna(df3).sum()

rut                0
primer_nombre      0
primer_apellido    0
sexo               4
edad               7
dtype: int64

## Eliminar guión atributo "rut"

In [25]:
Rdig = df2['rut'].astype(str).str[-1:] #devuelve el ultimo digito
Rdig

0     0
1     2
2     6
3     3
4     0
5     0
6     2
7     6
8     3
9     7
10    6
11    5
12    8
13    6
14    3
15    8
16    1
17    6
18    2
19    3
20    0
21    2
22    4
23    6
24    5
25    7
26    3
27    3
28    2
Name: rut, dtype: object

In [26]:
Rrut = df2['rut'].astype(str).str[:-2]
Rrut

0     18283486
1     14421402
2     17989836
3     19605255
4     13589393
5     17345287
6     17789709
7     16724776
8     11858264
9     14174140
10    13519635
11    14750398
12    10395210
13    16824747
14    17804114
15    16689237
16    16266568
17    17130465
18    12618978
19    15197110
20    15374301
21    11496755
22    15668643
23    14191904
24    19572300
25    19112555
26    18239715
27    13992695
28    12497449
Name: rut, dtype: object

In [27]:
R = Rrut+""+Rdig
R

0     182834860
1     144214022
2     179898366
3     196052553
4     135893930
5     173452870
6     177897092
7     167247766
8     118582643
9     141741407
10    135196356
11    147503985
12    103952108
13    168247476
14    178041143
15    166892378
16    162665681
17    171304656
18    126189782
19    151971103
20    153743010
21    114967552
22    156686434
23    141919046
24    195723005
25    191125557
26    182397153
27    139926953
28    124974492
Name: rut, dtype: object

In [28]:
df2['rut'] = R.astype(int) # asignamos al atributo rut la variable R, tipo entero

In [29]:
df = pd.merge(df1,df2, left_on='rut', right_on='rut') #funcion merge: unir
df

,rut,nombre_completo,sexo,edad_x,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,edad_y
0,182834860,Carmen Andrea Flores González,F,39.0,Carmen,Andrea,Flores,González,39.0
1,144214022,Alicia Marcela Aguirre Guerra,F,37.0,Alicia,Marcela,Aguirre,Guerra,37.0
2,179898366,Ernesto Luis Sabato Marin,M,36.0,Ernesto,Luis,Sabato,Marin,36.0
3,196052553,Iván Andrés Cabrera Marin,M,67.0,Iván,Andrés,Cabrera,Marin,67.0
4,135893930,Marcos Marcelo Hernandez Lozano,M,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN
5,173452870,Pedro Andrés Salas Pratto,M,59.0,Pedro,Andrés,Salas,Pratto,59.0
6,177897092,Lucas Andrés Pratto Marin,M,48.0,Lucas,Andrés,Pratto,Marin,48.0
7,167247766,Judas Jesús Prieto González,M,55.0,Judas,Jesús,Prieto,González,55.0
8,118582643,Luis Marcelo Diaz Carmela,M,67.0,Luis,Marcelo,Diaz,Carmela,67.0
9,141741407,Andrés Luis Poblete González,M,42.0,Andrés,Luis,Poblete,González,42.0
10,135196356,Juana Lucia Arco Estibarriga,F,35.0,Juana,Lucia,Arco,Estibarriga,NaN
11,147503985,Luisa Juana Rojas Chamorro,F,34.0,Luisa,Juana,Rojas,Chamorro,NaN
12,103952108,Irma Daniela González Rosas,F,41.0,Irma,Daniela,González,Rosas,NaN
13,168247476,Luisa Marcela Rojas Rodriguez,F,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0
14,178041143,Andrés Marcelo Carmona Carvajal,M,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0
15,166892378,Pedro Luis Carmona Rodriguez,NaN,NaN,Pedro,Luis,Carmona,Rodriguez,45.0
16,162665681,Juan Martin Del Potro Salazar,M,NaN,Juan,Martin,Del Potro,Salazar,59.0
17,171304656,Walter Montillo Soto González,M,NaN,Walter,Montillo,Soto,González,NaN
18,126189782,Marcelo Rios González González,NaN,NaN,Marcelo,Rios,González,González,NaN
19,151971103,Marcelo Francisco Soto Rojas,M,NaN,Marcelo,Francisco,Soto,Rojas,NaN
20,153743010,Iván Marcelo González Rosas,M,NaN,Iván,Marcelo,González,Rosas,NaN
21,114967552,Marcela María Zabaletta Zanetta,F,NaN,Marcela,María,Zabaletta,Zanetta,NaN
22,156686434,Andrea Marcela Quinchamali Marchan,NaN,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN
23,141919046,Macarena Daniela Rodriguez Altibán,F,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN
24,195723005,Roberta Sofia González Barros,F,NaN,Roberta,Sofia,González,Barros,NaN
25,191125557,Andrea Luisa Marin Roa,F,NaN,Andrea,Luisa,Marin,Roa,NaN
26,182397153,María María González González,F,NaN,María,María,González,González,NaN
27,139926953,Juana Luisa Marin Natero,F,NaN,Juana,Luisa,Marin,Natero,NaN
28,124974492,María De Los Ángeles Lozano Marin,F,NaN,María,De Los Ángeles,Lozano,Marin,NaN

In [30]:
df = pd.merge(df,df3, left_on='rut', right_on='rut')
df

,rut,nombre_completo,sexo_x,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,primer_nombre_y,primer_apellido_y,sexo_y,edad
0,182834860,Carmen Andrea Flores González,F,39.0,Carmen,Andrea,Flores,González,39.0,Carmen,Flores,1.0,39 años
1,144214022,Alicia Marcela Aguirre Guerra,F,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,Alicia,Aguirre,NaN,37 años
2,179898366,Ernesto Luis Sabato Marin,M,36.0,Ernesto,Luis,Sabato,Marin,36.0,Ernesto,Sabato,0.0,36 años
3,196052553,Iván Andrés Cabrera Marin,M,67.0,Iván,Andrés,Cabrera,Marin,67.0,Iván,Cabrera,0.0,67 años
4,135893930,Marcos Marcelo Hernandez Lozano,M,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,Marcos,Hernandez,0.0,66 años
5,173452870,Pedro Andrés Salas Pratto,M,59.0,Pedro,Andrés,Salas,Pratto,59.0,Pedro,Salas,0.0,59 años
6,177897092,Lucas Andrés Pratto Marin,M,48.0,Lucas,Andrés,Pratto,Marin,48.0,Lucas,Pratto,NaN,48 años
7,167247766,Judas Jesús Prieto González,M,55.0,Judas,Jesús,Prieto,González,55.0,Judas,Prieto,0.0,55 años
8,118582643,Luis Marcelo Diaz Carmela,M,67.0,Luis,Marcelo,Diaz,Carmela,67.0,Luis,Diaz,0.0,67 años
9,141741407,Andrés Luis Poblete González,M,42.0,Andrés,Luis,Poblete,González,42.0,Andrés,Poblete,0.0,NaN
10,135196356,Juana Lucia Arco Estibarriga,F,35.0,Juana,Lucia,Arco,Estibarriga,NaN,Juana,Arco,1.0,NaN
11,147503985,Luisa Juana Rojas Chamorro,F,34.0,Luisa,Juana,Rojas,Chamorro,NaN,Luisa,Rojas,1.0,34 años
12,103952108,Irma Daniela González Rosas,F,41.0,Irma,Daniela,González,Rosas,NaN,Irma,González,1.0,NaN
13,168247476,Luisa Marcela Rojas Rodriguez,F,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,Luisa,Rojas,1.0,NaN
14,178041143,Andrés Marcelo Carmona Carvajal,M,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,Andrés,Carmona,0.0,NaN
15,166892378,Pedro Luis Carmona Rodriguez,NaN,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,Pedro,Carmona,NaN,NaN
16,162665681,Juan Martin Del Potro Salazar,M,NaN,Juan,Martin,Del Potro,Salazar,59.0,Juan,Del Potro,0.0,NaN
17,171304656,Walter Montillo Soto González,M,NaN,Walter,Montillo,Soto,González,NaN,Walter,Soto,0.0,34 años
18,126189782,Marcelo Rios González González,NaN,NaN,Marcelo,Rios,González,González,NaN,Marcelo,González,0.0,50 años
19,151971103,Marcelo Francisco Soto Rojas,M,NaN,Marcelo,Francisco,Soto,Rojas,NaN,Marcelo,Soto,0.0,55 años
20,153743010,Iván Marcelo González Rosas,M,NaN,Iván,Marcelo,González,Rosas,NaN,Iván,González,0.0,64 años
21,114967552,Marcela María Zabaletta Zanetta,F,NaN,Marcela,María,Zabaletta,Zanetta,NaN,Marcela,Zabaletta,1.0,63 años
22,156686434,Andrea Marcela Quinchamali Marchan,NaN,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,Andrea,Quinchamali,NaN,52 años
23,141919046,Macarena Daniela Rodriguez Altibán,F,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,Macarena,Rodriguez,1.0,58 años
24,195723005,Roberta Sofia González Barros,F,NaN,Roberta,Sofia,González,Barros,NaN,Roberta,González,1.0,64 años
25,191125557,Andrea Luisa Marin Roa,F,NaN,Andrea,Luisa,Marin,Roa,NaN,Andrea,Marin,1.0,26 años
26,182397153,María María González González,F,NaN,María,María,González,González,NaN,María,González,1.0,61 años
27,139926953,Juana Luisa Marin Natero,F,NaN,Juana,Luisa,Marin,Natero,NaN,Juana,Marin,1.0,45 años
28,124974492,María De Los Ángeles Lozano Marin,F,NaN,María,De Los Ángeles,Lozano,Marin,NaN,María,Lozano,1.0,46 años

Eliminar atributos repetidos

In [31]:
df = df.drop(labels=["nombre_completo","primer_nombre_y","primer_apellido_y"], axis=1)
df

,rut,sexo_x,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,sexo_y,edad
0,182834860,F,39.0,Carmen,Andrea,Flores,González,39.0,1.0,39 años
1,144214022,F,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,NaN,37 años
2,179898366,M,36.0,Ernesto,Luis,Sabato,Marin,36.0,0.0,36 años
3,196052553,M,67.0,Iván,Andrés,Cabrera,Marin,67.0,0.0,67 años
4,135893930,M,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,0.0,66 años
5,173452870,M,59.0,Pedro,Andrés,Salas,Pratto,59.0,0.0,59 años
6,177897092,M,48.0,Lucas,Andrés,Pratto,Marin,48.0,NaN,48 años
7,167247766,M,55.0,Judas,Jesús,Prieto,González,55.0,0.0,55 años
8,118582643,M,67.0,Luis,Marcelo,Diaz,Carmela,67.0,0.0,67 años
9,141741407,M,42.0,Andrés,Luis,Poblete,González,42.0,0.0,NaN
10,135196356,F,35.0,Juana,Lucia,Arco,Estibarriga,NaN,1.0,NaN
11,147503985,F,34.0,Luisa,Juana,Rojas,Chamorro,NaN,1.0,34 años
12,103952108,F,41.0,Irma,Daniela,González,Rosas,NaN,1.0,NaN
13,168247476,F,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,1.0,NaN
14,178041143,M,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,0.0,NaN
15,166892378,NaN,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,NaN,NaN
16,162665681,M,NaN,Juan,Martin,Del Potro,Salazar,59.0,0.0,NaN
17,171304656,M,NaN,Walter,Montillo,Soto,González,NaN,0.0,34 años
18,126189782,NaN,NaN,Marcelo,Rios,González,González,NaN,0.0,50 años
19,151971103,M,NaN,Marcelo,Francisco,Soto,Rojas,NaN,0.0,55 años
20,153743010,M,NaN,Iván,Marcelo,González,Rosas,NaN,0.0,64 años
21,114967552,F,NaN,Marcela,María,Zabaletta,Zanetta,NaN,1.0,63 años
22,156686434,NaN,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,NaN,52 años
23,141919046,F,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,1.0,58 años
24,195723005,F,NaN,Roberta,Sofia,González,Barros,NaN,1.0,64 años
25,191125557,F,NaN,Andrea,Luisa,Marin,Roa,NaN,1.0,26 años
26,182397153,F,NaN,María,María,González,González,NaN,1.0,61 años
27,139926953,F,NaN,Juana,Luisa,Marin,Natero,NaN,1.0,45 años
28,124974492,F,NaN,María,De Los Ángeles,Lozano,Marin,NaN,1.0,46 años

Atributo "sexo_y"

In [32]:
df['sexo_y'] = df['sexo_y'].replace(1,'F')
df['sexo_y'] = df['sexo_y'].replace(0,'M')
df

,rut,sexo_x,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,sexo_y,edad
0,182834860,F,39.0,Carmen,Andrea,Flores,González,39.0,F,39 años
1,144214022,F,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,NaN,37 años
2,179898366,M,36.0,Ernesto,Luis,Sabato,Marin,36.0,M,36 años
3,196052553,M,67.0,Iván,Andrés,Cabrera,Marin,67.0,M,67 años
4,135893930,M,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,M,66 años
5,173452870,M,59.0,Pedro,Andrés,Salas,Pratto,59.0,M,59 años
6,177897092,M,48.0,Lucas,Andrés,Pratto,Marin,48.0,NaN,48 años
7,167247766,M,55.0,Judas,Jesús,Prieto,González,55.0,M,55 años
8,118582643,M,67.0,Luis,Marcelo,Diaz,Carmela,67.0,M,67 años
9,141741407,M,42.0,Andrés,Luis,Poblete,González,42.0,M,NaN
10,135196356,F,35.0,Juana,Lucia,Arco,Estibarriga,NaN,F,NaN
11,147503985,F,34.0,Luisa,Juana,Rojas,Chamorro,NaN,F,34 años
12,103952108,F,41.0,Irma,Daniela,González,Rosas,NaN,F,NaN
13,168247476,F,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,F,NaN
14,178041143,M,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,M,NaN
15,166892378,NaN,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,NaN,NaN
16,162665681,M,NaN,Juan,Martin,Del Potro,Salazar,59.0,M,NaN
17,171304656,M,NaN,Walter,Montillo,Soto,González,NaN,M,34 años
18,126189782,NaN,NaN,Marcelo,Rios,González,González,NaN,M,50 años
19,151971103,M,NaN,Marcelo,Francisco,Soto,Rojas,NaN,M,55 años
20,153743010,M,NaN,Iván,Marcelo,González,Rosas,NaN,M,64 años
21,114967552,F,NaN,Marcela,María,Zabaletta,Zanetta,NaN,F,63 años
22,156686434,NaN,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,NaN,52 años
23,141919046,F,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,F,58 años
24,195723005,F,NaN,Roberta,Sofia,González,Barros,NaN,F,64 años
25,191125557,F,NaN,Andrea,Luisa,Marin,Roa,NaN,F,26 años
26,182397153,F,NaN,María,María,González,González,NaN,F,61 años
27,139926953,F,NaN,Juana,Luisa,Marin,Natero,NaN,F,45 años
28,124974492,F,NaN,María,De Los Ángeles,Lozano,Marin,NaN,F,46 años

Unir los atributos "sexo_x" y "sexo_y"

In [33]:
ynan = np.where(df['sexo_x']==np.nan, df['sexo_y'], df['sexo_x'])
df['sexo'] = np.where(df['sexo_x']==df['sexo_y'], df['sexo_x'], ynan)
df

,rut,sexo_x,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,sexo_y,edad,sexo
0,182834860,F,39.0,Carmen,Andrea,Flores,González,39.0,F,39 años,F
1,144214022,F,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,NaN,37 años,F
2,179898366,M,36.0,Ernesto,Luis,Sabato,Marin,36.0,M,36 años,M
3,196052553,M,67.0,Iván,Andrés,Cabrera,Marin,67.0,M,67 años,M
4,135893930,M,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,M,66 años,M
5,173452870,M,59.0,Pedro,Andrés,Salas,Pratto,59.0,M,59 años,M
6,177897092,M,48.0,Lucas,Andrés,Pratto,Marin,48.0,NaN,48 años,M
7,167247766,M,55.0,Judas,Jesús,Prieto,González,55.0,M,55 años,M
8,118582643,M,67.0,Luis,Marcelo,Diaz,Carmela,67.0,M,67 años,M
9,141741407,M,42.0,Andrés,Luis,Poblete,González,42.0,M,NaN,M
10,135196356,F,35.0,Juana,Lucia,Arco,Estibarriga,NaN,F,NaN,F
11,147503985,F,34.0,Luisa,Juana,Rojas,Chamorro,NaN,F,34 años,F
12,103952108,F,41.0,Irma,Daniela,González,Rosas,NaN,F,NaN,F
13,168247476,F,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,F,NaN,F
14,178041143,M,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,M,NaN,M
15,166892378,NaN,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,NaN,NaN,NaN
16,162665681,M,NaN,Juan,Martin,Del Potro,Salazar,59.0,M,NaN,M
17,171304656,M,NaN,Walter,Montillo,Soto,González,NaN,M,34 años,M
18,126189782,NaN,NaN,Marcelo,Rios,González,González,NaN,M,50 años,NaN
19,151971103,M,NaN,Marcelo,Francisco,Soto,Rojas,NaN,M,55 años,M
20,153743010,M,NaN,Iván,Marcelo,González,Rosas,NaN,M,64 años,M
21,114967552,F,NaN,Marcela,María,Zabaletta,Zanetta,NaN,F,63 años,F
22,156686434,NaN,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,NaN,52 años,NaN
23,141919046,F,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,F,58 años,F
24,195723005,F,NaN,Roberta,Sofia,González,Barros,NaN,F,64 años,F
25,191125557,F,NaN,Andrea,Luisa,Marin,Roa,NaN,F,26 años,F
26,182397153,F,NaN,María,María,González,González,NaN,F,61 años,F
27,139926953,F,NaN,Juana,Luisa,Marin,Natero,NaN,F,45 años,F
28,124974492,F,NaN,María,De Los Ángeles,Lozano,Marin,NaN,F,46 años,F

In [34]:
df = df.drop(labels=["sexo_x","sexo_y"], axis=1)
df

,rut,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,edad,sexo
0,182834860,39.0,Carmen,Andrea,Flores,González,39.0,39 años,F
1,144214022,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,37 años,F
2,179898366,36.0,Ernesto,Luis,Sabato,Marin,36.0,36 años,M
3,196052553,67.0,Iván,Andrés,Cabrera,Marin,67.0,67 años,M
4,135893930,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,66 años,M
5,173452870,59.0,Pedro,Andrés,Salas,Pratto,59.0,59 años,M
6,177897092,48.0,Lucas,Andrés,Pratto,Marin,48.0,48 años,M
7,167247766,55.0,Judas,Jesús,Prieto,González,55.0,55 años,M
8,118582643,67.0,Luis,Marcelo,Diaz,Carmela,67.0,67 años,M
9,141741407,42.0,Andrés,Luis,Poblete,González,42.0,NaN,M
10,135196356,35.0,Juana,Lucia,Arco,Estibarriga,NaN,NaN,F
11,147503985,34.0,Luisa,Juana,Rojas,Chamorro,NaN,34 años,F
12,103952108,41.0,Irma,Daniela,González,Rosas,NaN,NaN,F
13,168247476,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,NaN,F
14,178041143,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,NaN,M
15,166892378,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,NaN,NaN
16,162665681,NaN,Juan,Martin,Del Potro,Salazar,59.0,NaN,M
17,171304656,NaN,Walter,Montillo,Soto,González,NaN,34 años,M
18,126189782,NaN,Marcelo,Rios,González,González,NaN,50 años,NaN
19,151971103,NaN,Marcelo,Francisco,Soto,Rojas,NaN,55 años,M
20,153743010,NaN,Iván,Marcelo,González,Rosas,NaN,64 años,M
21,114967552,NaN,Marcela,María,Zabaletta,Zanetta,NaN,63 años,F
22,156686434,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,52 años,NaN
23,141919046,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,58 años,F
24,195723005,NaN,Roberta,Sofia,González,Barros,NaN,64 años,F
25,191125557,NaN,Andrea,Luisa,Marin,Roa,NaN,26 años,F
26,182397153,NaN,María,María,González,González,NaN,61 años,F
27,139926953,NaN,Juana,Luisa,Marin,Natero,NaN,45 años,F
28,124974492,NaN,María,De Los Ángeles,Lozano,Marin,NaN,46 años,F

In [35]:
df['sexo'] = df['sexo'].fillna(' ') #eliminar datos NA del atributo "sexo"
df

,rut,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,edad,sexo
0,182834860,39.0,Carmen,Andrea,Flores,González,39.0,39 años,F
1,144214022,37.0,Alicia,Marcela,Aguirre,Guerra,37.0,37 años,F
2,179898366,36.0,Ernesto,Luis,Sabato,Marin,36.0,36 años,M
3,196052553,67.0,Iván,Andrés,Cabrera,Marin,67.0,67 años,M
4,135893930,66.0,Marcos,Marcelo,Hernandez,Lozano,NaN,66 años,M
5,173452870,59.0,Pedro,Andrés,Salas,Pratto,59.0,59 años,M
6,177897092,48.0,Lucas,Andrés,Pratto,Marin,48.0,48 años,M
7,167247766,55.0,Judas,Jesús,Prieto,González,55.0,55 años,M
8,118582643,67.0,Luis,Marcelo,Diaz,Carmela,67.0,67 años,M
9,141741407,42.0,Andrés,Luis,Poblete,González,42.0,NaN,M
10,135196356,35.0,Juana,Lucia,Arco,Estibarriga,NaN,NaN,F
11,147503985,34.0,Luisa,Juana,Rojas,Chamorro,NaN,34 años,F
12,103952108,41.0,Irma,Daniela,González,Rosas,NaN,NaN,F
13,168247476,NaN,Luisa,Marcela,Rojas,Rodriguez,18.0,NaN,F
14,178041143,NaN,Andrés,Marcelo,Carmona,Carvajal,23.0,NaN,M
15,166892378,NaN,Pedro,Luis,Carmona,Rodriguez,45.0,NaN,
16,162665681,NaN,Juan,Martin,Del Potro,Salazar,59.0,NaN,M
17,171304656,NaN,Walter,Montillo,Soto,González,NaN,34 años,M
18,126189782,NaN,Marcelo,Rios,González,González,NaN,50 años,
19,151971103,NaN,Marcelo,Francisco,Soto,Rojas,NaN,55 años,M
20,153743010,NaN,Iván,Marcelo,González,Rosas,NaN,64 años,M
21,114967552,NaN,Marcela,María,Zabaletta,Zanetta,NaN,63 años,F
22,156686434,NaN,Andrea,Marcela,Quinchamali,Marchan,NaN,52 años,
23,141919046,NaN,Macarena,Daniela,Rodriguez,Altibán,NaN,58 años,F
24,195723005,NaN,Roberta,Sofia,González,Barros,NaN,64 años,F
25,191125557,NaN,Andrea,Luisa,Marin,Roa,NaN,26 años,F
26,182397153,NaN,María,María,González,González,NaN,61 años,F
27,139926953,NaN,Juana,Luisa,Marin,Natero,NaN,45 años,F
28,124974492,NaN,María,De Los Ángeles,Lozano,Marin,NaN,46 años,F

# Atributo "edad"

In [36]:
df.dtypes

rut                    int64
edad_x               float64
primer_nombre_x       object
segundo_nombre        object
primer_apellido_x     object
segundo_apellido      object
edad_y               float64
edad                  object
sexo                  object
dtype: object

In [37]:
df['edad_x'] = df['edad_x'].astype(str).str[:-2]
df['edad_y'] = df['edad_y'].astype(str).str[:-2]
df

,rut,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,edad,sexo
0,182834860,39,Carmen,Andrea,Flores,González,39,39 años,F
1,144214022,37,Alicia,Marcela,Aguirre,Guerra,37,37 años,F
2,179898366,36,Ernesto,Luis,Sabato,Marin,36,36 años,M
3,196052553,67,Iván,Andrés,Cabrera,Marin,67,67 años,M
4,135893930,66,Marcos,Marcelo,Hernandez,Lozano,n,66 años,M
5,173452870,59,Pedro,Andrés,Salas,Pratto,59,59 años,M
6,177897092,48,Lucas,Andrés,Pratto,Marin,48,48 años,M
7,167247766,55,Judas,Jesús,Prieto,González,55,55 años,M
8,118582643,67,Luis,Marcelo,Diaz,Carmela,67,67 años,M
9,141741407,42,Andrés,Luis,Poblete,González,42,NaN,M
10,135196356,35,Juana,Lucia,Arco,Estibarriga,n,NaN,F
11,147503985,34,Luisa,Juana,Rojas,Chamorro,n,34 años,F
12,103952108,41,Irma,Daniela,González,Rosas,n,NaN,F
13,168247476,n,Luisa,Marcela,Rojas,Rodriguez,18,NaN,F
14,178041143,n,Andrés,Marcelo,Carmona,Carvajal,23,NaN,M
15,166892378,n,Pedro,Luis,Carmona,Rodriguez,45,NaN,
16,162665681,n,Juan,Martin,Del Potro,Salazar,59,NaN,M
17,171304656,n,Walter,Montillo,Soto,González,n,34 años,M
18,126189782,n,Marcelo,Rios,González,González,n,50 años,
19,151971103,n,Marcelo,Francisco,Soto,Rojas,n,55 años,M
20,153743010,n,Iván,Marcelo,González,Rosas,n,64 años,M
21,114967552,n,Marcela,María,Zabaletta,Zanetta,n,63 años,F
22,156686434,n,Andrea,Marcela,Quinchamali,Marchan,n,52 años,
23,141919046,n,Macarena,Daniela,Rodriguez,Altibán,n,58 años,F
24,195723005,n,Roberta,Sofia,González,Barros,n,64 años,F
25,191125557,n,Andrea,Luisa,Marin,Roa,n,26 años,F
26,182397153,n,María,María,González,González,n,61 años,F
27,139926953,n,Juana,Luisa,Marin,Natero,n,45 años,F
28,124974492,n,María,De Los Ángeles,Lozano,Marin,n,46 años,F

In [38]:
y_nan = np.where(df['edad_x']=='n', df['edad_y'], df['edad_x'])
df['edad_x'] = np.where(df['edad_x']==df['edad_y'], df['edad_x'], y_nan)
df

,rut,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,edad,sexo
0,182834860,39,Carmen,Andrea,Flores,González,39,39 años,F
1,144214022,37,Alicia,Marcela,Aguirre,Guerra,37,37 años,F
2,179898366,36,Ernesto,Luis,Sabato,Marin,36,36 años,M
3,196052553,67,Iván,Andrés,Cabrera,Marin,67,67 años,M
4,135893930,66,Marcos,Marcelo,Hernandez,Lozano,n,66 años,M
5,173452870,59,Pedro,Andrés,Salas,Pratto,59,59 años,M
6,177897092,48,Lucas,Andrés,Pratto,Marin,48,48 años,M
7,167247766,55,Judas,Jesús,Prieto,González,55,55 años,M
8,118582643,67,Luis,Marcelo,Diaz,Carmela,67,67 años,M
9,141741407,42,Andrés,Luis,Poblete,González,42,NaN,M
10,135196356,35,Juana,Lucia,Arco,Estibarriga,n,NaN,F
11,147503985,34,Luisa,Juana,Rojas,Chamorro,n,34 años,F
12,103952108,41,Irma,Daniela,González,Rosas,n,NaN,F
13,168247476,18,Luisa,Marcela,Rojas,Rodriguez,18,NaN,F
14,178041143,23,Andrés,Marcelo,Carmona,Carvajal,23,NaN,M
15,166892378,45,Pedro,Luis,Carmona,Rodriguez,45,NaN,
16,162665681,59,Juan,Martin,Del Potro,Salazar,59,NaN,M
17,171304656,n,Walter,Montillo,Soto,González,n,34 años,M
18,126189782,n,Marcelo,Rios,González,González,n,50 años,
19,151971103,n,Marcelo,Francisco,Soto,Rojas,n,55 años,M
20,153743010,n,Iván,Marcelo,González,Rosas,n,64 años,M
21,114967552,n,Marcela,María,Zabaletta,Zanetta,n,63 años,F
22,156686434,n,Andrea,Marcela,Quinchamali,Marchan,n,52 años,
23,141919046,n,Macarena,Daniela,Rodriguez,Altibán,n,58 años,F
24,195723005,n,Roberta,Sofia,González,Barros,n,64 años,F
25,191125557,n,Andrea,Luisa,Marin,Roa,n,26 años,F
26,182397153,n,María,María,González,González,n,61 años,F
27,139926953,n,Juana,Luisa,Marin,Natero,n,45 años,F
28,124974492,n,María,De Los Ángeles,Lozano,Marin,n,46 años,F

In [39]:
y_nan_ = np.where(df['edad_x']=='n', df['edad'], df['edad_x']+' años')
df['edad'] = np.where(df['edad_x']+' años'==df['edad'], df['edad'], y_nan_)
df

,rut,edad_x,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad_y,edad,sexo
0,182834860,39,Carmen,Andrea,Flores,González,39,39 años,F
1,144214022,37,Alicia,Marcela,Aguirre,Guerra,37,37 años,F
2,179898366,36,Ernesto,Luis,Sabato,Marin,36,36 años,M
3,196052553,67,Iván,Andrés,Cabrera,Marin,67,67 años,M
4,135893930,66,Marcos,Marcelo,Hernandez,Lozano,n,66 años,M
5,173452870,59,Pedro,Andrés,Salas,Pratto,59,59 años,M
6,177897092,48,Lucas,Andrés,Pratto,Marin,48,48 años,M
7,167247766,55,Judas,Jesús,Prieto,González,55,55 años,M
8,118582643,67,Luis,Marcelo,Diaz,Carmela,67,67 años,M
9,141741407,42,Andrés,Luis,Poblete,González,42,42 años,M
10,135196356,35,Juana,Lucia,Arco,Estibarriga,n,35 años,F
11,147503985,34,Luisa,Juana,Rojas,Chamorro,n,34 años,F
12,103952108,41,Irma,Daniela,González,Rosas,n,41 años,F
13,168247476,18,Luisa,Marcela,Rojas,Rodriguez,18,18 años,F
14,178041143,23,Andrés,Marcelo,Carmona,Carvajal,23,23 años,M
15,166892378,45,Pedro,Luis,Carmona,Rodriguez,45,45 años,
16,162665681,59,Juan,Martin,Del Potro,Salazar,59,59 años,M
17,171304656,n,Walter,Montillo,Soto,González,n,34 años,M
18,126189782,n,Marcelo,Rios,González,González,n,50 años,
19,151971103,n,Marcelo,Francisco,Soto,Rojas,n,55 años,M
20,153743010,n,Iván,Marcelo,González,Rosas,n,64 años,M
21,114967552,n,Marcela,María,Zabaletta,Zanetta,n,63 años,F
22,156686434,n,Andrea,Marcela,Quinchamali,Marchan,n,52 años,
23,141919046,n,Macarena,Daniela,Rodriguez,Altibán,n,58 años,F
24,195723005,n,Roberta,Sofia,González,Barros,n,64 años,F
25,191125557,n,Andrea,Luisa,Marin,Roa,n,26 años,F
26,182397153,n,María,María,González,González,n,61 años,F
27,139926953,n,Juana,Luisa,Marin,Natero,n,45 años,F
28,124974492,n,María,De Los Ángeles,Lozano,Marin,n,46 años,F

In [40]:
df = df.drop(labels=["edad_x","edad_y"], axis=1)
df

,rut,primer_nombre_x,segundo_nombre,primer_apellido_x,segundo_apellido,edad,sexo
0,182834860,Carmen,Andrea,Flores,González,39 años,F
1,144214022,Alicia,Marcela,Aguirre,Guerra,37 años,F
2,179898366,Ernesto,Luis,Sabato,Marin,36 años,M
3,196052553,Iván,Andrés,Cabrera,Marin,67 años,M
4,135893930,Marcos,Marcelo,Hernandez,Lozano,66 años,M
5,173452870,Pedro,Andrés,Salas,Pratto,59 años,M
6,177897092,Lucas,Andrés,Pratto,Marin,48 años,M
7,167247766,Judas,Jesús,Prieto,González,55 años,M
8,118582643,Luis,Marcelo,Diaz,Carmela,67 años,M
9,141741407,Andrés,Luis,Poblete,González,42 años,M
10,135196356,Juana,Lucia,Arco,Estibarriga,35 años,F
11,147503985,Luisa,Juana,Rojas,Chamorro,34 años,F
12,103952108,Irma,Daniela,González,Rosas,41 años,F
13,168247476,Luisa,Marcela,Rojas,Rodriguez,18 años,F
14,178041143,Andrés,Marcelo,Carmona,Carvajal,23 años,M
15,166892378,Pedro,Luis,Carmona,Rodriguez,45 años,
16,162665681,Juan,Martin,Del Potro,Salazar,59 años,M
17,171304656,Walter,Montillo,Soto,González,34 años,M
18,126189782,Marcelo,Rios,González,González,50 años,
19,151971103,Marcelo,Francisco,Soto,Rojas,55 años,M
20,153743010,Iván,Marcelo,González,Rosas,64 años,M
21,114967552,Marcela,María,Zabaletta,Zanetta,63 años,F
22,156686434,Andrea,Marcela,Quinchamali,Marchan,52 años,
23,141919046,Macarena,Daniela,Rodriguez,Altibán,58 años,F
24,195723005,Roberta,Sofia,González,Barros,64 años,F
25,191125557,Andrea,Luisa,Marin,Roa,26 años,F
26,182397153,María,María,González,González,61 años,F
27,139926953,Juana,Luisa,Marin,Natero,45 años,F
28,124974492,María,De Los Ángeles,Lozano,Marin,46 años,F

In [41]:
df.columns = ['Id','Nombre_1','Nombre_2','Apellido_1','Apellido_2','Edad','Genero']
df
#renombrar atributos

,Id,Nombre_1,Nombre_2,Apellido_1,Apellido_2,Edad,Genero
0,182834860,Carmen,Andrea,Flores,González,39 años,F
1,144214022,Alicia,Marcela,Aguirre,Guerra,37 años,F
2,179898366,Ernesto,Luis,Sabato,Marin,36 años,M
3,196052553,Iván,Andrés,Cabrera,Marin,67 años,M
4,135893930,Marcos,Marcelo,Hernandez,Lozano,66 años,M
5,173452870,Pedro,Andrés,Salas,Pratto,59 años,M
6,177897092,Lucas,Andrés,Pratto,Marin,48 años,M
7,167247766,Judas,Jesús,Prieto,González,55 años,M
8,118582643,Luis,Marcelo,Diaz,Carmela,67 años,M
9,141741407,Andrés,Luis,Poblete,González,42 años,M
10,135196356,Juana,Lucia,Arco,Estibarriga,35 años,F
11,147503985,Luisa,Juana,Rojas,Chamorro,34 años,F
12,103952108,Irma,Daniela,González,Rosas,41 años,F
13,168247476,Luisa,Marcela,Rojas,Rodriguez,18 años,F
14,178041143,Andrés,Marcelo,Carmona,Carvajal,23 años,M
15,166892378,Pedro,Luis,Carmona,Rodriguez,45 años,
16,162665681,Juan,Martin,Del Potro,Salazar,59 años,M
17,171304656,Walter,Montillo,Soto,González,34 años,M
18,126189782,Marcelo,Rios,González,González,50 años,
19,151971103,Marcelo,Francisco,Soto,Rojas,55 años,M
20,153743010,Iván,Marcelo,González,Rosas,64 años,M
21,114967552,Marcela,María,Zabaletta,Zanetta,63 años,F
22,156686434,Andrea,Marcela,Quinchamali,Marchan,52 años,
23,141919046,Macarena,Daniela,Rodriguez,Altibán,58 años,F
24,195723005,Roberta,Sofia,González,Barros,64 años,F
25,191125557,Andrea,Luisa,Marin,Roa,26 años,F
26,182397153,María,María,González,González,61 años,F
27,139926953,Juana,Luisa,Marin,Natero,45 años,F
28,124974492,María,De Los Ángeles,Lozano,Marin,46 años,F

# Guardar dataframe

In [42]:
df.to_excel('Clientes.xlsx', sheet_name='HojaPrueba')

In [43]:
df_sub1 = pd.read_excel('Clientes.xlsx')
df_sub1

,Unnamed: 0,Id,Nombre_1,Nombre_2,Apellido_1,Apellido_2,Edad,Genero
0,0,182834860,Carmen,Andrea,Flores,González,39 años,F
1,1,144214022,Alicia,Marcela,Aguirre,Guerra,37 años,F
2,2,179898366,Ernesto,Luis,Sabato,Marin,36 años,M
3,3,196052553,Iván,Andrés,Cabrera,Marin,67 años,M
4,4,135893930,Marcos,Marcelo,Hernandez,Lozano,66 años,M
5,5,173452870,Pedro,Andrés,Salas,Pratto,59 años,M
6,6,177897092,Lucas,Andrés,Pratto,Marin,48 años,M
7,7,167247766,Judas,Jesús,Prieto,González,55 años,M
8,8,118582643,Luis,Marcelo,Diaz,Carmela,67 años,M
9,9,141741407,Andrés,Luis,Poblete,González,42 años,M
10,10,135196356,Juana,Lucia,Arco,Estibarriga,35 años,F
11,11,147503985,Luisa,Juana,Rojas,Chamorro,34 años,F
12,12,103952108,Irma,Daniela,González,Rosas,41 años,F
13,13,168247476,Luisa,Marcela,Rojas,Rodriguez,18 años,F
14,14,178041143,Andrés,Marcelo,Carmona,Carvajal,23 años,M
15,15,166892378,Pedro,Luis,Carmona,Rodriguez,45 años,
16,16,162665681,Juan,Martin,Del Potro,Salazar,59 años,M
17,17,171304656,Walter,Montillo,Soto,González,34 años,M
18,18,126189782,Marcelo,Rios,González,González,50 años,
19,19,151971103,Marcelo,Francisco,Soto,Rojas,55 años,M
20,20,153743010,Iván,Marcelo,González,Rosas,64 años,M
21,21,114967552,Marcela,María,Zabaletta,Zanetta,63 años,F
22,22,156686434,Andrea,Marcela,Quinchamali,Marchan,52 años,
23,23,141919046,Macarena,Daniela,Rodriguez,Altibán,58 años,F
24,24,195723005,Roberta,Sofia,González,Barros,64 años,F
25,25,191125557,Andrea,Luisa,Marin,Roa,26 años,F
26,26,182397153,María,María,González,González,61 años,F
27,27,139926953,Juana,Luisa,Marin,Natero,45 años,F
28,28,124974492,María,De Los Ángeles,Lozano,Marin,46 años,F

In [44]:
df.to_csv('Clientes.csv', sep=',')

In [46]:
df_sub2 = pd.read_csv('Clientes.csv', sep=',')
df_sub2.head()

,Unnamed: 0,Id,Nombre_1,Nombre_2,Apellido_1,Apellido_2,Edad,Genero
0,0,182834860,Carmen,Andrea,Flores,González,39 años,F
1,1,144214022,Alicia,Marcela,Aguirre,Guerra,37 años,F
2,2,179898366,Ernesto,Luis,Sabato,Marin,36 años,M
3,3,196052553,Iván,Andrés,Cabrera,Marin,67 años,M
4,4,135893930,Marcos,Marcelo,Hernandez,Lozano,66 años,M